angular.module 'imagewikiFrontend', [
  'ngAnimate'
  'toastr'
  'ngResource'
  'ui.router'
  'angular-jwt'
  'angular-loading-bar'
  'angular-storage'
  'ngFileUpload'
  'ui.bootstrap.datetimepicker'
  'angularUtils.directives.dirPagination'
  'validation.match'
  'vcRecaptcha'
  'ngTagsInput'
]
